#!/bin/sh
con=~/.config
date=$(date +%d-%m-%Y)
git submodule update --init --recursive

#move files into .config
if [[ $con/nvim ]]; then 
  mv $con/nvim $con/nvim.old-$date
  cp -r nvim $con/
else
  cp -r nvim $con/
fi

if [[ "~/.zshrc" ]]; then 
  mv ~/.zshrc ~/.zshrc.old-$date
  cp -r zsh $con/
  ln -s $con/zsh/.zshrc ~/.zshrc
  source $con/zsh/.zshrc
else
  cp -r zsh $con/
  ln -s $con/zsh/.zshrc ~/.zshrc
  source $con/zsh/.zshrc
fi

if [[ "$con/gh" ]]; then 
  mv $con/gh $con/gh.old-$date
  cp -r gh $con/
else
  cp -r gh $con/
fi

if [[ "$con/powerlevel10k" ]]; then 
  mv $con/powerlevel10k $con/powerlevel10k.old-$date
  cp -r powerlevel10k $con/
else
  cp -r powerlevel10k $con/
fi


if [[ "$con/kitty" ]]; then 
  mv $con/kitty $con/kitty.old-$date
  cp -r kitty $con/
else
  cp -r kitty $con/
fi

sudo cp -r Caskaydia-Cove /usr/share/fonts/
sudo cp -r Boon /usr/share/fonts/
sudo cp -r JetBrainsMono /usr/share/fonts/



sudo cp -r logo-ls-files usr/bin/
sudo ln -s /usr/bin/logo-ls-files/logo-ls /usr/bin/logo-ls


