#!/bin/sh
con=~/.config
date=$(date +%d-%m-%Y)
git submodule update --init --recursive

#move files into .config
if [[ $con/nvim ]]; then 
  mv $con/nvim $con/nvim.old-$date
  mv nvim $con/
else
  mv nvim $con/
fi

if [[ ~/.zshrc]]; then 
  mv ~/.zshrc ~/.zshrc.old-$date
  mv zsh $con/
  ln -s $con/zsh/.zshrc ~/.zshrc
  source $con/zsh/.zshrc
else
  mv zsh $con/
  ln -s $con/zsh/.zshrc ~/.zshrc
  source $con/zsh/.zshrc
fi

if [[ $con/gh]]; then 
  mv $con/gh $con/gh.old-$date
  mv gh $con/
else
  mv gh $con/
fi

if [[ $con/powerlevel10k]]; then 
  mv $con/powerlevel10k $con/powerlevel10k.old-$date
  mv powerlevel10k $con/
else
  mv powerlevel10k $con/
fi


if [[ $con/kitty ]]; then 
  mv $con/kitty $con/kitty.old-$date
  mv kitty $con/
else
  mv kitty $con/
fi

sudo mv SymbolsNerdFonts /etc/fonts/
sudo mv Caskaydia-Cove /etc/fonts/
sudo mv Boon /etc/fonts/
sudo mv JetBrainsMono /etc/fonts/



sudo mv logo-ls-files usr/bin/
sudo ln -s /usr/bin/logo-ls-files/logo-ls /usr/bin/logo-ls


