#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

preview() {
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
}

TEMPDIR=${XDG_CACHE_HOME:-$HOME/.cache}

file="$1"; shift
case "$(basename "$file" | tr '[a-z]' '[a-z]')" in
    *.tar*) tar tf "$file" ;;
    *.zip) unzip -l "$file" ;;
    *.rar) unrar l "$file" ;;
    *.7z) 7z l "$file" ;;

    *.avi|*.mp4|*.mkv)
        thumbnail="$tempdir/thumbnail.png"
        ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
        preview "$thumbnail"
        ;;

    *.pdf)
        CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
        [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
        image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
        ;;
    *.jpg|*.jpeg|*.png|*.bmp|*.webp)
        preview "$file"
        ;;

    *.ttf|*.otf|*.woff)
        thumbnail="$TEMPDIR/thumbnail.png"
        fontpreview -i "$file" -o "$thumbnail"
        preview "$thumbnail"
        ;;

    *.svg)
        thumbnail="$TEMPDIR/thumbnail.png"
        convert "$file" "$thumbnail"
        preview "$thumbnail"
        ;;

    *) bat --terminal-width "$(($x-2))" -f "$file" ;;

esac
return 127 # nonzero retcode required for lf previews to reload

